/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author vanhv
 */
public class CalculatorForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorForm
     */
    public CalculatorForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btnMC = new javax.swing.JButton();
        btnMR = new javax.swing.JButton();
        btnMS = new javax.swing.JButton();
        btnMAdd = new javax.swing.JButton();
        btnMSub = new javax.swing.JButton();
        btnBackSpace = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnNegate = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnMultiple = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnPercent = new javax.swing.JButton();
        btnInvert = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSub = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtDisplay.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        txtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDisplay.setText("0");
        txtDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtDisplay.setFocusable(false);

        btnMC.setBackground(new java.awt.Color(153, 204, 255));
        btnMC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMC.setText("MC");
        btnMC.setEnabled(false);
        btnMC.setFocusable(false);

        btnMR.setBackground(new java.awt.Color(153, 204, 255));
        btnMR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMR.setText("MR");
        btnMR.setEnabled(false);
        btnMR.setFocusable(false);

        btnMS.setBackground(new java.awt.Color(153, 204, 255));
        btnMS.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMS.setText("MS");
        btnMS.setEnabled(false);
        btnMS.setFocusable(false);

        btnMAdd.setBackground(new java.awt.Color(153, 204, 255));
        btnMAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMAdd.setText("M+");
        btnMAdd.setEnabled(false);
        btnMAdd.setFocusable(false);

        btnMSub.setBackground(new java.awt.Color(153, 204, 255));
        btnMSub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMSub.setText("M-");
        btnMSub.setEnabled(false);
        btnMSub.setFocusable(false);

        btnBackSpace.setBackground(new java.awt.Color(153, 204, 255));
        btnBackSpace.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBackSpace.setText("←");
        btnBackSpace.setActionCommand("");
        btnBackSpace.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBackSpace.setFocusable(false);

        btnCE.setBackground(new java.awt.Color(153, 204, 255));
        btnCE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCE.setText("CE");
        btnCE.setActionCommand("");
        btnCE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCE.setFocusable(false);

        btnC.setBackground(new java.awt.Color(153, 204, 255));
        btnC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnC.setText("C");
        btnC.setActionCommand("");
        btnC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnC.setFocusable(false);

        btnNegate.setBackground(new java.awt.Color(153, 204, 255));
        btnNegate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNegate.setText("±");
        btnNegate.setActionCommand("");
        btnNegate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNegate.setFocusable(false);

        btnSqrt.setBackground(new java.awt.Color(153, 204, 255));
        btnSqrt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSqrt.setText("√");
        btnSqrt.setActionCommand("");
        btnSqrt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSqrt.setFocusable(false);

        btnNum7.setBackground(new java.awt.Color(153, 204, 255));
        btnNum7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum7.setText("7");
        btnNum7.setActionCommand("");
        btnNum7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum7.setFocusable(false);

        btnNum4.setBackground(new java.awt.Color(153, 204, 255));
        btnNum4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum4.setText("4");
        btnNum4.setActionCommand("");
        btnNum4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum4.setFocusable(false);

        btnNum5.setBackground(new java.awt.Color(153, 204, 255));
        btnNum5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum5.setText("5");
        btnNum5.setActionCommand("");
        btnNum5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum5.setFocusable(false);

        btnNum8.setBackground(new java.awt.Color(153, 204, 255));
        btnNum8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum8.setText("8");
        btnNum8.setActionCommand("");
        btnNum8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum8.setFocusable(false);

        btnNum9.setBackground(new java.awt.Color(153, 204, 255));
        btnNum9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum9.setText("9");
        btnNum9.setActionCommand("");
        btnNum9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum9.setFocusable(false);

        btnNum6.setBackground(new java.awt.Color(153, 204, 255));
        btnNum6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum6.setText("6");
        btnNum6.setActionCommand("");
        btnNum6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum6.setFocusable(false);

        btnMultiple.setBackground(new java.awt.Color(153, 204, 255));
        btnMultiple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMultiple.setText("*");
        btnMultiple.setActionCommand("");
        btnMultiple.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMultiple.setFocusable(false);

        btnDivide.setBackground(new java.awt.Color(153, 204, 255));
        btnDivide.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setActionCommand("");
        btnDivide.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivide.setFocusable(false);

        btnPercent.setBackground(new java.awt.Color(153, 204, 255));
        btnPercent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPercent.setText("%");
        btnPercent.setActionCommand("");
        btnPercent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPercent.setFocusable(false);

        btnInvert.setBackground(new java.awt.Color(153, 204, 255));
        btnInvert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInvert.setText("1/x");
        btnInvert.setActionCommand("");
        btnInvert.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInvert.setFocusable(false);

        btnNum1.setBackground(new java.awt.Color(153, 204, 255));
        btnNum1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum1.setText("1");
        btnNum1.setActionCommand("");
        btnNum1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum1.setFocusable(false);

        btnNum0.setBackground(new java.awt.Color(153, 204, 255));
        btnNum0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum0.setText("0");
        btnNum0.setActionCommand("");
        btnNum0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum0.setFocusable(false);

        btnNum2.setBackground(new java.awt.Color(153, 204, 255));
        btnNum2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum2.setText("2");
        btnNum2.setActionCommand("");
        btnNum2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum2.setFocusable(false);

        btnNum3.setBackground(new java.awt.Color(153, 204, 255));
        btnNum3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNum3.setText("3");
        btnNum3.setActionCommand("");
        btnNum3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNum3.setFocusable(false);

        btnDot.setBackground(new java.awt.Color(153, 204, 255));
        btnDot.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDot.setText(".");
        btnDot.setActionCommand("");
        btnDot.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDot.setFocusable(false);

        btnAdd.setBackground(new java.awt.Color(153, 204, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setText("+");
        btnAdd.setActionCommand("");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.setFocusable(false);

        btnSub.setBackground(new java.awt.Color(153, 204, 255));
        btnSub.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSub.setText("-");
        btnSub.setActionCommand("");
        btnSub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSub.setFocusable(false);

        btnResult.setBackground(new java.awt.Color(153, 204, 255));
        btnResult.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResult.setText("=");
        btnResult.setActionCommand("");
        btnResult.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnResult.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDisplay)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNegate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInvert, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMS, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMSub, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNegate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiple, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInvert, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSub, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("View");
        jMenu1.setFocusable(false);
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setFocusable(false);
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenu3.setFocusable(false);
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackSpace;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnInvert;
    private javax.swing.JButton btnMAdd;
    private javax.swing.JButton btnMC;
    private javax.swing.JButton btnMR;
    private javax.swing.JButton btnMS;
    private javax.swing.JButton btnMSub;
    private javax.swing.JButton btnMultiple;
    private javax.swing.JButton btnNegate;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton btnPercent;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnSub;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public JButton getBtnBackSpace() {
        return btnBackSpace;
    }

    public void setBtnBackSpace(JButton btnBackSpace) {
        this.btnBackSpace = btnBackSpace;
    }

    public JButton getBtnC() {
        return btnC;
    }

    public void setBtnC(JButton btnC) {
        this.btnC = btnC;
    }

    public JButton getBtnCE() {
        return btnCE;
    }

    public void setBtnCE(JButton btnCE) {
        this.btnCE = btnCE;
    }

    public JButton getBtnDivide() {
        return btnDivide;
    }

    public void setBtnDivide(JButton btnDivide) {
        this.btnDivide = btnDivide;
    }

    public JButton getBtnDot() {
        return btnDot;
    }

    public void setBtnDot(JButton btnDot) {
        this.btnDot = btnDot;
    }

    public JButton getBtnInvert() {
        return btnInvert;
    }

    public void setBtnInvert(JButton btnInvert) {
        this.btnInvert = btnInvert;
    }

    public JButton getBtnMAdd() {
        return btnMAdd;
    }

    public void setBtnMAdd(JButton btnMAdd) {
        this.btnMAdd = btnMAdd;
    }

    public JButton getBtnMC() {
        return btnMC;
    }

    public void setBtnMC(JButton btnMC) {
        this.btnMC = btnMC;
    }

    public JButton getBtnMR() {
        return btnMR;
    }

    public void setBtnMR(JButton btnMR) {
        this.btnMR = btnMR;
    }

    public JButton getBtnMS() {
        return btnMS;
    }

    public void setBtnMS(JButton btnMS) {
        this.btnMS = btnMS;
    }

    public JButton getBtnMSub() {
        return btnMSub;
    }

    public void setBtnMSub(JButton btnMSub) {
        this.btnMSub = btnMSub;
    }

    public JButton getBtnMultiple() {
        return btnMultiple;
    }

    public void setBtnMultiple(JButton btnMultiple) {
        this.btnMultiple = btnMultiple;
    }

    public JButton getBtnNegate() {
        return btnNegate;
    }

    public void setBtnNegate(JButton btnNegate) {
        this.btnNegate = btnNegate;
    }

    public JButton getBtnNum0() {
        return btnNum0;
    }

    public void setBtnNum0(JButton btnNum0) {
        this.btnNum0 = btnNum0;
    }

    public JButton getBtnNum1() {
        return btnNum1;
    }

    public void setBtnNum1(JButton btnNum1) {
        this.btnNum1 = btnNum1;
    }

    public JButton getBtnNum2() {
        return btnNum2;
    }

    public void setBtnNum2(JButton btnNum2) {
        this.btnNum2 = btnNum2;
    }

    public JButton getBtnNum3() {
        return btnNum3;
    }

    public void setBtnNum3(JButton btnNum3) {
        this.btnNum3 = btnNum3;
    }

    public JButton getBtnNum4() {
        return btnNum4;
    }

    public void setBtnNum4(JButton btnNum4) {
        this.btnNum4 = btnNum4;
    }

    public JButton getBtnNum5() {
        return btnNum5;
    }

    public void setBtnNum5(JButton btnNum5) {
        this.btnNum5 = btnNum5;
    }

    public JButton getBtnNum6() {
        return btnNum6;
    }

    public void setBtnNum6(JButton btnNum6) {
        this.btnNum6 = btnNum6;
    }

    public JButton getBtnNum7() {
        return btnNum7;
    }

    public void setBtnNum7(JButton btnNum7) {
        this.btnNum7 = btnNum7;
    }

    public JButton getBtnNum8() {
        return btnNum8;
    }

    public void setBtnNum8(JButton btnNum8) {
        this.btnNum8 = btnNum8;
    }

    public JButton getBtnNum9() {
        return btnNum9;
    }

    public void setBtnNum9(JButton btnNum9) {
        this.btnNum9 = btnNum9;
    }

    public JButton getBtnPercent() {
        return btnPercent;
    }

    public void setBtnPercent(JButton btnPercent) {
        this.btnPercent = btnPercent;
    }

    public JButton getBtnResult() {
        return btnResult;
    }

    public void setBtnResult(JButton btnResult) {
        this.btnResult = btnResult;
    }

    public JButton getBtnSqrt() {
        return btnSqrt;
    }

    public void setBtnSqrt(JButton btnSqrt) {
        this.btnSqrt = btnSqrt;
    }

    public JButton getBtnSub() {
        return btnSub;
    }

    public void setBtnSub(JButton btnSub) {
        this.btnSub = btnSub;
    }

    public JTextField getTxtDisplay() {
        return txtDisplay;
    }

    public void setTxtDisplay(JTextField txtDisplay) {
        this.txtDisplay = txtDisplay;
    }

}
