/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JPanel;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author vanhv
 */
public class FormColorSlider extends javax.swing.JFrame {

    /**
     * Creates new form FormSliderColor
     */
    public FormColorSlider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenTxt = new javax.swing.JTextField();
        redSlider = new javax.swing.JSlider();
        redTxt = new javax.swing.JTextField();
        blueTxt = new javax.swing.JTextField();
        colorPanel = new javax.swing.JPanel();
        greenSlider = new javax.swing.JSlider();
        blueSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        greenTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        greenTxt.setForeground(new java.awt.Color(0, 255, 51));
        greenTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        greenTxt.setFocusable(false);

        redSlider.setMaximum(255);
        redSlider.setValue(57);
        redSlider.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        redSlider.setName(""); // NOI18N
        redSlider.setValueIsAdjusting(true);

        redTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        redTxt.setForeground(new java.awt.Color(255, 0, 0));
        redTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        redTxt.setFocusable(false);

        blueTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        blueTxt.setForeground(new java.awt.Color(0, 102, 255));
        blueTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        blueTxt.setFocusable(false);

        colorPanel.setBackground(new java.awt.Color(255, 255, 255));
        colorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        javax.swing.GroupLayout colorPanelLayout = new javax.swing.GroupLayout(colorPanel);
        colorPanel.setLayout(colorPanelLayout);
        colorPanelLayout.setHorizontalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );
        colorPanelLayout.setVerticalGroup(
            colorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        greenSlider.setMaximum(255);
        greenSlider.setValue(180);
        greenSlider.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        greenSlider.setValueIsAdjusting(true);

        blueSlider.setMaximum(255);
        blueSlider.setToolTipText("");
        blueSlider.setValue(84);
        blueSlider.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10)));
        blueSlider.setValueIsAdjusting(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(redSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greenSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(blueSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greenTxt)
                    .addComponent(redTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(blueTxt))
                .addGap(0, 0, 0)
                .addComponent(colorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(redSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(redTxt))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(greenTxt)
                    .addComponent(greenSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(blueSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(colorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider blueSlider;
    private javax.swing.JTextField blueTxt;
    private javax.swing.JPanel colorPanel;
    private javax.swing.JSlider greenSlider;
    private javax.swing.JTextField greenTxt;
    private javax.swing.JSlider redSlider;
    private javax.swing.JTextField redTxt;
    // End of variables declaration//GEN-END:variables

    public JSlider getBlueSlider() {
        return blueSlider;
    }

    public void setBlueSlider(JSlider blueSlider) {
        this.blueSlider = blueSlider;
    }

    public JTextField getBlueTxt() {
        return blueTxt;
    }

    public void setBlueTxt(JTextField blueTxt) {
        this.blueTxt = blueTxt;
    }

    public JPanel getColorPanel() {
        return colorPanel;
    }

    public void setColorPanel(JPanel colorPanel) {
        this.colorPanel = colorPanel;
    }

    public JSlider getGreenSlider() {
        return greenSlider;
    }

    public void setGreenSlider(JSlider greenSlider) {
        this.greenSlider = greenSlider;
    }

    public JTextField getGreenTxt() {
        return greenTxt;
    }

    public void setGreenTxt(JTextField greenTxt) {
        this.greenTxt = greenTxt;
    }

    public JSlider getRedSlider() {
        return redSlider;
    }

    public void setRedSlider(JSlider redSlider) {
        this.redSlider = redSlider;
    }

    public JTextField getRedTxt() {
        return redTxt;
    }

    public void setRedTxt(JTextField redTxt) {
        this.redTxt = redTxt;
    }

}
